[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    cache-control = '''
    public,
    max-age=31536000'''

[[headers]]
  for = "/assets/js/*"
  [headers.values]
    cache-control = '''
    public,
    max-age=5184000'''

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    cache-control = '''
    public,
    max-age=5184000'''

[[headers]]
  for = "*.jpg"
  [headers.values]
    cache-control = '''
    public,
    max-age=15552000'''

[[headers]]
  for = "*.png"
  [headers.values]
    cache-control = '''
    public,
    max-age=15552000'''
